rosbag:
  input_bag_path: '/home/bzeren/projects/labs/data/rosbags/rosbag2_2024_03_22-18_27_21/rosbag2_2024_03_22-18_27_21_0-001.mcap'
  output_bag_paht: '/home/bzeren/projects/labs/data/rosbags/rosbag2_2024_03_22-18_27_21/output'
  output_save_compressed_image: True
  output_storage_id: 'sqlite3' # 'sqlite3' or 'mcap'
grounding_dino:
  config_path: './GroundingDINO_SwinB.cfg.py'
  checkpoint_path: './groundingdino_swinb_cogcoor.pth'
  box_threshold: 0.1
  text_threshold: 0.1
  nms_threshold: 0.1
segment_anything:
  encoder_version: 'vit_h'
  checkpoint_path: './sam_vit_h_4b8939.pth'
openclip:
  model_name: 'ViT-B-32'
  pretrained_model: 'laion2b_s34b_b79k'
  score_threshold: 0.8
bbox_validation:
  iou_threshold: 0.9
blur:
  kernel_size: 21
  sigma_x: 0